# Generated by Django 3.2.2 on 2021-05-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos_importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(default='produto', max_length=60)),
                ('quantidade', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=60, null=True)),
                ('preco', models.DecimalField(decimal_places=3, max_digits=6)),
                ('frete', models.DecimalField(decimal_places=3, max_digits=6)),
                ('data_entrega', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos_loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(default='0ACB', max_length=45)),
                ('nome', models.CharField(default='produto', max_length=45)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=3, max_digits=6)),
                ('status', models.CharField(default='esperando produto', max_length=45)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.importacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='importacao',
            name='produto_importacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produtos_importacao'),
        ),
    ]
