# Generated by Django 3.2.2 on 2021-05-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos_importacao',
            options={'verbose_name_plural': 'Produtos_importacao'},
        ),
        migrations.AlterModelOptions(
            name='produtos_loja',
            options={'verbose_name_plural': 'Produtos_da_Loja'},
        ),
        migrations.RemoveField(
            model_name='produtos_importacao',
            name='data_entrega',
        ),
    ]
