# Generated by Django 3.2.2 on 2021-10-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20210512_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos_importacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='produtos_importacao',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
