# Generated by Django 3.2.2 on 2021-10-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20211018_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos_loja',
            name='importacao',
        ),
    ]
