# Generated by Django 3.2.2 on 2021-11-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_produtos_loja_importacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exportador', models.CharField(default='Nome:', max_length=50)),
                ('pais', models.CharField(default='País:', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Importacao',
        ),
    ]
