# Generated by Django 3.2.2 on 2021-11-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20211105_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos_importacao',
            name='exportadores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.exportadores'),
        ),
    ]
