# Generated by Django 3.2.2 on 2021-11-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_produtos_importacao_exportadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos_importacao',
            name='exportadores',
        ),
        migrations.AddField(
            model_name='produtos_importacao',
            name='exportadores',
            field=models.ManyToManyField(to='estoque.Exportadores'),
        ),
    ]
