# Generated by Django 3.2.2 on 2021-11-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_auto_20211105_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos_importacao',
            name='exportadores',
        ),
        migrations.AddField(
            model_name='produtos_importacao',
            name='nome_exportador',
            field=models.CharField(default='Nome:', max_length=50),
        ),
        migrations.AddField(
            model_name='produtos_importacao',
            name='pais',
            field=models.CharField(default='País:', max_length=50),
        ),
        migrations.DeleteModel(
            name='Exportadores',
        ),
    ]
