# Generated by Django 3.2.2 on 2021-11-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_auto_20211105_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos_importacao',
            name='codigo',
            field=models.CharField(default='0ACB', max_length=45),
        ),
    ]
