# Generated by Django 3.2.2 on 2021-11-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_produtos_importacao_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos_importacao',
            name='status',
            field=models.CharField(default='esperando produto', max_length=45),
        ),
        migrations.AlterField(
            model_name='produtos_loja',
            name='status',
            field=models.CharField(default='produto em estoque', max_length=45),
        ),
    ]
