version: "3"
services:
  server:
    build: .
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    links:
      - db
    environment:
      DB_HOST: localhost
      DB_PWD: and010500
      DB_USER: dba
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: Seven_sails
      MYSQL_PASSWORD: and010500
      MYSQL_ROOT_PASSWORD: and010500
      MYSQL_HOST: localhost

    ports:
      - "33066:33006"